### ISSUE TITLE
BC break

### ISSUE THREAD

**Issue by szymach** [fsi-open/admin-positionable-bundle#23]
#22 has introduced a BC break, forcing people to switch to "fsi/admin-bundle": "~2.0.*@dev".

**Comment by norzechowicz** [comment]
dont create issues if you have no idea what are talking about. admin-positionable-bundle master has no stable version how anything can be considered then as a BC breake?

**Comment by szymach** [comment]
Well it has an alias 1.1.x-dev doesn't it? So it's meant to work with admin-bundle branch 1.1? Or am I mistaken? Because right now I can't update my dependencies because this only package demands admin in 2.0.*@dev.

**Comment by norzechowicz** [comment]
Alias means that you are using master and master is not stable so there is no BC Break here. Update your project to use admin ``2.0.*@dev`` version or downgrade dependency from admin-positionable-bundle to ``1.0.0``.

**Comment by chives** [comment]
@norzechowicz this issue is not about specific project but exists in every project that uses more that one of fsi-open's bundles. We need to leave master branch with `1.1-dev` alias in order to allow smooth upgrading of subsequent packages. Your change requires to upgrade versions of all other bundles at once.

**Comment by norzechowicz** [comment]
Well thats how using unstable bundles ends for projects. We can't keep ``1.1-dev`` on master branch because it will make impossible to use admin-positionable-bundle (and other unstalbe bundles) with most up to date admin-bundle which is the purpose of master branch. 
Projects that can't be updated can be locked to specific commit on this branch (one commit before #22) or updated to admin 2.0.*@dev (which is not a problem because there are no BC Breakes in 2.0@dev according to 1.1@dev) or downgraded to admin-positionable and admin bundle 1.0.* version

**Comment by szymach** [comment]
Why don't we simply copy the solution from admin bundle? Create a 1.1 branch and make the 1.1-dev point at that branch, which will make the upgrade process much more smooth. We have no idea how long upgrading other packages will take. This way there will be no need to upgrade every project with hard-coded commit hash and once all packages have been updated, you update your dependencies once.

**Comment by norzechowicz** [comment]
it will also require from you to update composer.json of your project anyway. You gonna need to change admin-positionable-bundle dependency from "dev-master" to "1.1@dev" so how is that different from updating dependency of admin-bundle from "1.1.*@dev" into "2.0.*@dev"?

**Comment by szymach** [comment]
My dependency is already `1.1@dev`, that's the thing. Also, I am using doctrine extensions bundle, translatable bundle, resource repository bundle etc. which all are dependant on admin bundle in version ~1.1@dev.

**Comment by norzechowicz** [comment]
All other bundles should also be updated like this one, just for now you should lock to specific commint your project if you realy need to update it now.

**Comment by szymach** [comment]
Fine, but shouldn't you also change the alias in composer.json to 2.0-dev, like in admin-bundle?
